### ISSUE TITLE
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

### ISSUE THREAD

**Issue by vorburger** [schmutterer/gradle-openjpa#8]
This old Gradle plug-in used to work well in ancient pre-historic old Gradle 2.10 version, but is broken under new current Gradle versions such as 5.2.1; see https://issues.apache.org/jira/browse/FINERACT-700 for full stack trace.

https://github.com/radcortez/openjpa-gradle-plugin may be a viable alternative you could point users to.

**Comment by vorburger** [comment]
```
Execution failed for task ':openjpaEnhance'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getProperty(Unknown Source)
        at at.schmutterer.oss.gradle.openjpa.OpenJpaPlugin.collectURLs(OpenJpaPlugin.groovy:61)
        at at.schmutterer.oss.gradle.openjpa.OpenJpaPlugin$_apply_closure1.doCall(OpenJpaPlugin.groovy:32)
```
